TARGET = pdp

CXX = g++
CXX_FLAGS = -Wall -pedantic -Wextra -std=c++20 -fopenmp -O3

MKDIR = mkdir -p
BUILD_DIR = build

.PHONY: all
all: compile

.PHONY: compile
compile: $(TARGET)

.PHONY: run
run: $(TARGET)
	./$(TARGET) graf_mro/graf_10_5.txt 5 10 974

$(TARGET): $(BUILD_DIR)/main.o $(BUILD_DIR)/Graph.o $(BUILD_DIR)/TestData.o $(BUILD_DIR)/Edge.o
	$(CXX) $(CXX_FLAGS) $^ -o $@ 

$(BUILD_DIR)/%.o: src/%.cpp
	$(MKDIR) $(BUILD_DIR)
	$(CXX) $(CXX_FLAGS) $< -c -o $@

.PHONY: clean
clean:
	rm -rf $(TARGET) $(BUILD_DIR)/ 2>/dev/null

#depencencies (generated by "g++ -MM src/*.cpp")
$(BUILD_DIR)Edge.o: src/Edge.cpp
$(BUILD_DIR)Graph.o: src/Graph.cpp src/Edge.cpp
$(BUILD_DIR)TestData.o: src/TestData.cpp
$(BUILD_DIR)main.o: src/main.cpp src/Graph.cpp src/Edge.cpp src/TestData.cpp

#inspired by PA2 stream https://youtu.be/qmgZF5ijax8
